### ISSUE TITLE
iPad, swift - unable to use some view controllers

### ISSUE THREAD

**Issue by Kaven01** [Adonit/LAMY-iPadOS-SDK#1]
I am trying to enable LAMY by set of view controllers provided by this SDK, and have issues when using some of them. I imported the framework according to the wiki ( https://github.com/Adonit/LAMY-iPadOS-SDK/wiki/Getting-Started-Guide ), which works. I then run into issues when trying to instantiate provided view controllers using 
`UIStoryboard.instantiateLamyViewController(withIdentifier:)`

I can successfully create these controllers: LamyViewControllerUnifiedStylusConnectionAndSettingsIdentifier, LamyViewControllerDebugStatusIdentifier, LamyViewControllerPressToConnectIdentifier, LamyViewControllerUnifiedStatusButtonAndConnectionAndSettingsIdentifier . These work as expected, can be placed in my views etc.

However if I add some of the following controllers, the code does not compile : LamyViewControllerBatteryIdentifier, LamyViewControllerShortCutsIdentifier, LamyViewControllerWritingStyleIdentifier . The error issued by xcode during compile is (for battery controller): 

> Undefined symbol: _LamyViewControllerBatteryIdentifier

Strange is that xcode autocomplete sees these identifiers (eg.  LamyViewControllerBatteryIdentifier ), and xcode does not show any errors during writing code. Error appears only during compilation.

**Comment by adonitDevel** [comment]
Hi @Kaven01  thanks for your feedback
This issue has been fixed by version 1.0.2
Thanks.

**Comment by Kaven01** [comment]
> Hi @Kaven01 thanks for your feedback This issue has been fixed by version 1.0.2 Thanks.
That is better, I can now use  LamyViewControllerBatteryIdentifier and LamyViewControllerShortCutsIdentifier,

However LamyViewControllerWritingStyleIdentifier is still not available. This time error in xcode is "Cannot find 'LamyViewControllerWritingStyleIdentifier' in scope". It appears immediatelly, not later during build as before. The problem is with this one identifier only, all others work.

**Comment by adonitDevel** [comment]
Hi @Kaven01, 
The LamyViewControllerWritingStyleIdentifier is a legacy feature, so I removed it.
Sorry for your inconvenience.

**Comment by Kaven01** [comment]
Oh, I see. OK, no need for this UI then.
